### ISSUE TITLE
Mirror View Mode: Black game view screen

### ISSUE THREAD

**Issue by nitz** [ValveSoftware/unity-xr-plugin#107]
Hello!

I'm reporting this because the readme asked to!

Here's my current `Open VR Settings.asset`:
```yaml
%YAML 1.1
%TAG !u! tag:unity3d.com,2011:
--- !u!114 &11400000
MonoBehaviour:
  m_ObjectHideFlags: 0
  m_CorrespondingSourceObject: {fileID: 0}
  m_PrefabInstance: {fileID: 0}
  m_PrefabAsset: {fileID: 0}
  m_GameObject: {fileID: 0}
  m_Enabled: 1
  m_EditorHideFlags: 0
  m_Script: {fileID: 11500000, guid: 7a32bfe54d957ec4581fa4a630f1647a, type: 3}
  m_Name: Open VR Settings
  m_EditorClassIdentifier: 
  PromptToUpgradePackage: 1
  PromptToUpgradePreviewPackages: 1
  SkipPromptForVersion: 
  StereoRenderingMode: 1
  InitializationType: 1
  EditorAppKey: application.generated.unity.<application-name-here>.exe
  ActionManifestFileRelativeFilePath: StreamingAssets\SteamVR\actions.json
  MirrorView: 3
  PreInit: 1
  HasCopiedDefaults: 0
```

Since switching to Mirror View Mode "Open VR", I get a black game view both in the editor and in builds. The actual headset display  (Vive Pro Eye) appears fine. In editor, when starting to 'Play', it seems a frame is rendered in the game view before going black. 

My color space is set to `Linear`, and I'm using Single Pass Instanced as a rendering mode. I'm using Unity 2020.3.21f1, on a Windows 10 Pro (19043.1288) machine.

I'd love to provide any other details I can to help track down the issue, but I'll just go back to Left Eye mirroring in the meantime.

Cheers!
